time_zone: Africa/Johannesburg
# my preferred time format
## Date Time infomation
### https://gosamples.dev/date-time-format-cheatsheet/
time_format: Mon, 2006-01-02 @ 15:04:05
git_executable: /usr/bin/git
go_executable: /usr/bin/go
ffmpeg_executable: /usr/bin/ffmpeg
debug_mode: false
use_github_binaries: false
architecture: ""
telegram:
    bot_token:
    api_url: http://localhost:4887
    sudo_users_id:
        - XYYYXXXXXXXXX
    owner_id: XYYYXXXXXXXXX
    target_chat_id: -100ZZZZZZAAAAAAAA
    self_hosted_api: true
    skip_video_stickers: false
    skip_setting_commands: false
    send_my_presence: false
    send_my_read_receipts: true
    silent_confirmation: true
    confirmation_type: emoji
    emoji_confirmation: null
    skip_startup_message: true
    spoiler_as_viewonce: true
    reactions: true
whatsapp:
    login_database:
        type: sqlite3
        url: file:wawebstore.db?_foreign_keys=on
    sticker_metadata:
        pack_name: AkitaInu
        author_name: AkitaInu
    session_name: AkitaInuBrowser
    tag_all_allowed_groups: []
    ignore_chats: []
    status_ignored_chats:
        - "27XXXXXXXXX"
    skip_documents: false
    skip_images: false
    skip_gifs: false
    skip_videos: false
    skip_voice_notes: false
    skip_audios: false
    skip_status: false
    skip_stickers: false
    skip_contacts: false
    skip_locations: false
    skip_profile_picture_updates: false
    skip_group_settings_updates: false
    skip_chat_details: false
    send_revoked_message_updates: true
    whatsmeow_debug_mode: false
    send_my_messages_from_other_devices: false
    create_thread_for_info_updates: true
database:
    dbname: 
    host: localhost
    password: 
    port:
    time_zone: Africa/Johannesburg
    type: 
    user: 
